name: Secret
on: push
jobs:
  display_values:
    runs-on: ubunut-latest
    outputs:
      MON_RETOUR: ${{ steps.stepReturns.outputs.result}}
    steps:
      - run: |
          echo "${{secrets.DB_PASSWORD}}
          echo "${{vars.Version}}
      - name : Step
        id : stepReturn
        uses: actions/github-script@v7.0.1
        with:
          # The script to run
          script: return "Mon retoru";
  display_return:
    runs-on: ubuntu-latest
    needs: [display_values]
    steps:
      - run: echo ${{needs.display_values.outputs.MON_RETOUR}}
          
